/*  

    Program to generate a PostScript file for the morpholigical 
    evolution of the composition profile governed by the variable 
    mobility Cahn-Hilliard equation.

    Copyright (C) 2020  Abhinav Roy, M.P. Gururajan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.


*/


#include<stdio.h>
#include<stdlib.h>

void ps_file(char* file_name, char* ps_file_name, int Nx, int Ny, int N)
{
  FILE *fpw, *fpr;
  int i,j;
  int temp;
  double *c;

  c = (double*)malloc((size_t)Nx*Ny* sizeof(double));

  if ((fpr = fopen(file_name,"rb")) == NULL)
  {
    printf("Unable to open data file. Exiting.");
    exit(0);
  }
  else
  {
    fpr = fopen(file_name,"rb");
  }

  fread(&c[0], sizeof(double),(size_t) Nx*Ny, fpr);
  (void) fclose(fpr);
  fflush(fpr);
  if ((fpw = fopen(ps_file_name,"wb")) == NULL)
  {
    printf("Unable to open ps file. Exiting.");
    exit(0);
  }
  else
  {
    fpw = fopen(ps_file_name,"wb");
  }
/** The preamble to the ps file **/

// fprintf(fpw,"%%!PS-Adobe-2.0 EPSF-2.0\n");
fprintf(fpw,"%%%%Generated by C-program output.\n");
fprintf(fpw,"%%%%Creator: Abhinav Roy, MP Gururajan.\n");
fprintf(fpw,"%%%%Title: Microstructure\n");
fprintf(fpw,"%%%%BoundingBox: 0 0 256 256\n");
fprintf(fpw,"0 0 translate\n");
fprintf(fpw,"0 rotate\n");
fprintf(fpw,"256 256 scale\n");
fprintf(fpw,"/picstr %d string def\n",N);
fprintf(fpw,"%d %d 8 [%d 0 0 -%d 0 %d]\n",N,N,N,N,N);
fprintf(fpw,"{currentfile picstr readhexstring pop} image\n");
  //Generating the ps file
  for(i=0; i < Nx; ++i)
  {
	   for(j=0; j < Ny; ++j)
     {
		     temp = (int)(255.0*c[j+Ny*i]);
		     if(temp < 0)
			{ temp = 1;}
		     if(temp > 255) 
			{temp = 255;}
		     fprintf(fpw,"%02x",temp);
	}
	fprintf(fpw,"\n");
 }
 
fprintf(fpw,"grestore\n");
fprintf(fpw,"showpage\n");
fprintf(fpw,"%%%%EOF\n");
(void) fclose(fpw);
 fflush(fpw);
 free(c);
 
}
